// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR5n3Vwa8ZfCKteZl3IXjVqXd8ts6_ymQ',
    appId: '1:683480234424:web:f3ee249be9676f3285f74d',
    messagingSenderId: '683480234424',
    projectId: 'flutter-try-eno',
    authDomain: 'flutter-try-eno.firebaseapp.com',
    storageBucket: 'flutter-try-eno.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW47eYmMbLQA_qvzZ8pnYiZIig-eBl2Do',
    appId: '1:683480234424:android:33ec80cd3940122f85f74d',
    messagingSenderId: '683480234424',
    projectId: 'flutter-try-eno',
    storageBucket: 'flutter-try-eno.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApoViTdOZPwZe15YX9j3EGV-msc_S28-4',
    appId: '1:683480234424:ios:4c9639b94a802e1c85f74d',
    messagingSenderId: '683480234424',
    projectId: 'flutter-try-eno',
    storageBucket: 'flutter-try-eno.appspot.com',
    iosClientId: '683480234424-9ilmvib2getf1q7dvk11dvtg45p2lb92.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApoViTdOZPwZe15YX9j3EGV-msc_S28-4',
    appId: '1:683480234424:ios:4c9639b94a802e1c85f74d',
    messagingSenderId: '683480234424',
    projectId: 'flutter-try-eno',
    storageBucket: 'flutter-try-eno.appspot.com',
    iosClientId: '683480234424-9ilmvib2getf1q7dvk11dvtg45p2lb92.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSample',
  );
}
